In [ ]:
import sys
print(sys.executable)

: 

In [1]:
import torch
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])
print(x + y)


tensor([5., 7., 9.])


In [6]:
z = torch.randn(3, 100)
print(type(z))
print(z.max())

<class 'torch.Tensor'>
tensor(2.7642)


In [10]:
x = torch.randn(2, 12)       # 形状 (2, 12)

# 变换为 (2, 3, 4) — 相当于把 12 拆成 3×4
y = x.view(2, 3, 4)
print(y)                # torch.Size([2, 3, 4])

# 用 -1 让 PyTorch 自动推算
z = x.view(2, -1, 4)         # -1 的位置自动推算为 3
print(z)                # torch.Size([2, 3, 4])


tensor([[[-0.4165,  0.1388,  0.4313,  0.8608],
         [-0.3324,  0.4216, -0.7776,  0.5548],
         [ 0.1206,  1.1610, -0.2003, -1.5755]],

        [[ 0.3009,  0.4445, -0.5569, -0.5561],
         [ 0.5123,  0.4461, -1.0055, -0.9025],
         [ 0.1032, -1.2949, -1.0765,  0.0495]]])
tensor([[[-0.4165,  0.1388,  0.4313,  0.8608],
         [-0.3324,  0.4216, -0.7776,  0.5548],
         [ 0.1206,  1.1610, -0.2003, -1.5755]],

        [[ 0.3009,  0.4445, -0.5569, -0.5561],
         [ 0.5123,  0.4461, -1.0055, -0.9025],
         [ 0.1032, -1.2949, -1.0765,  0.0495]]])


In [11]:
print(torch.tensor([1, 2, 3]))


tensor([1, 2, 3])


In [16]:
x = torch.tensor([[0,0,0],[0,0,0]])
y = torch.zeros(2,3)
z = torch.tensor([[[0,1,0],[0,0,0]],
                  [[0,0,0],[0,0,0]]]) #tensor()只接受一个数据参数
print(x,y,z,z[0,0,1])
print(z.ndim)

tensor([[0, 0, 0],
        [0, 0, 0]]) tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[[0, 1, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]]) tensor(1)
3


In [18]:
x = torch.tensor([1.0, 2.0, 3.0])
y = x.view(1, -1)  # 将 x 转换为形状为 (1, 3) 的二维张量
print(y)  # 只能有一个 -1，表示自动推断维度大小

tensor([[1., 2., 3.]])


In [28]:
A = torch.arange(1,3) # 生成一个从 start 到 end-1 的一维张量
B = torch.arange(2,4)
C = torch.arange(6)
D = C.view(2, -1) # 将 C 转换为形状为 (2, 1) 的二维张量
print(A @ B)
print(torch.matmul(A, B))
print(A,D)
print(D.ndim)

tensor(8)
tensor(8)
tensor([1, 2]) tensor([[0, 1, 2],
        [3, 4, 5]])
2


In [30]:
a = torch.randn(2, 3)
b = torch.randn(3, 2)
print(a,b,a @ b)  # 矩阵乘法，结果形状为 (2, 2)

tensor([[-0.6095,  1.5621, -0.3406],
        [ 0.0386, -0.0667, -0.4727]]) tensor([[ 1.0023,  1.5010],
        [-0.2750, -0.5810],
        [-1.0917,  1.6491]]) tensor([[-0.6687, -2.3841],
        [ 0.5730, -0.6828]])


In [ ]:
w = torch.tensor([3.0,4.0], requires_grad=True)
y = w ** 2 + 2 * w + 1
y.backward() # 计算梯度（求导数），保存在 w.grad 中
print(w.grad)  # 输出梯度值，即 y 对 w 的导数 dy/dw = 2*w + 2

RuntimeError: grad can be implicitly created only for scalar outputs

In [45]:
import torch
import torch.nn as nn

class SimpleLayer(nn.Module):  # 继承 PyTorch 神经网络模块
    def __init__(self, input_size, output_size): #构造方法，也是一种函数
        super().__init__()    # 初始化父类
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):     # 定义输入如何变成输出
        return self.linear(x) #linear只处理最后一维，其他维度保持不变

layer = SimpleLayer(768, 256)  # 创建层
x = torch.randn(2, 768)       # 2 个样本，每个有 768 个特征
output = layer(x)            # 自动执行 forward
print(output.shape)         # torch.Size([2, 256])

tensor([[0.1780, 0.7241]], grad_fn=<AddmmBackward0>)
SimpleLayer(
  (linear): Linear(in_features=3, out_features=2, bias=True)
)


In [52]:
import torch 
import torch.nn as nn
class Simplelayer(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self, x):
        return self.linear(x)
layer = Simplelayer(768, 256)
x = torch.randn(3, 768)
output = layer(x)
print(output.shape)

torch.Size([3, 256])


In [53]:
linear = nn.Linear(768, 256)
x = torch.randn(3, 768)
y = linear(x)
print(y.shape)

torch.Size([3, 256])


In [78]:
embed = nn.Embedding(num_embeddings= 6400, embedding_dim= 768)
token_ids = torch.tensor([234, 567, 891])
vectors = embed(token_ids)
print(vectors.shape)
print(vectors)


torch.Size([3, 768])
tensor([[ 0.8686,  0.5340,  1.0544,  ..., -0.8595, -2.1106, -0.1025],
        [-0.0681,  1.3266, -1.3288,  ..., -0.1305, -0.6473, -0.0916],
        [-0.9123,  0.4601,  0.7460,  ..., -0.7930,  0.8858, -1.2330]],
       grad_fn=<EmbeddingBackward0>)
<built-in method size of Tensor object at 0x0000023818278640>


In [64]:
loss_fn = nn.CrossEntropyLoss()
logits = torch.tensor([5.0, 0.0, 0.0, 0.0])
target = torch.tensor([0])
loss = loss_fn(logits, target)
print(loss)

tensor(0.0200)


In [65]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"使用设备: {device}")


使用设备: cpu


In [ ]:
import torch
import torch.nn as nn

# === 1. 准备数据 ===
text = "hello world hello pytorch hello deep learning"
chars = sorted(set(text))            # 所有不重复的字符
vocab_size = len(chars)               # 词表大小
char_to_id = {c: i for i, c in enumerate(chars)} # 生成{字母:索引}的字典
id_to_char = {i: c for i, c in enumerate(chars)} # 生成{索引:字母}的字典

data = torch.tensor([char_to_id[c] for c in text]) # 原始输入数据中的各个字母（空格）在字符表中的编号

# === 2. 定义模型 ===
class TinyLM(nn.Module):
    def __init__(self, vocab_size, hidden_size=32):  # hidden_size是每个字符的向量参数量，可以自己选择
        super().__init__()
        self.embed = nn.Embedding(vocab_size, hidden_size)
        self.linear1 = nn.Linear(hidden_size, hidden_size) # 同维度乘一个权重矩阵
        self.linear2 = nn.Linear(hidden_size, vocab_size) #？

    def forward(self, x):
        h = self.embed(x)               # token_id → 向量
        h = torch.relu(self.linear1(h))  # 非线性变换(激活)，让神经网络表达复杂关系。
        logits = self.linear2(h)         # 向量 → 词表大小的分数
        return logits # logits : 未归一化类别分数

# === 3. 训练 ===
model = TinyLM(vocab_size)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.CrossEntropyLoss()

for epoch in range(500):
    inputs = data[:-1]     # "hello world ... learnin"
    targets = data[1:]     # "ello world ... learning"

    logits = model(inputs)
    loss = loss_fn(logits, targets) #这个时候，data已经是索引集了

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if (epoch + 1) % 50 == 0: # 每50次打印一次成果
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

# === 4. 生成 ===
with torch.no_grad(): # with 用处是搭建一个条件环境，离开这个缩进后，该条件自动消失
    seed = char_to_id['h']  # 给模型一个起点
    result = ['h']
    current = torch.tensor([seed]) 

    for _ in range(4):
        logits = model(current)
        probs = torch.softmax(logits, dim=-1) # dim=-1表示对最后一维,也就是有候选字符做softmax概率分布
        next_id = int(torch.multinomial(probs, 1).item()) # multinomial是按照分布随机采样下一个输出字符
        result.append(id_to_char[next_id])
        current = torch.tensor([next_id])

    print("生成结果:", ''.join(result))


Epoch 40, Loss: 0.3466
Epoch 80, Loss: 0.3466
Epoch 120, Loss: 0.3466
Epoch 160, Loss: 0.3466
Epoch 200, Loss: 0.3466
Epoch 240, Loss: 0.3466
Epoch 280, Loss: 0.3471
Epoch 320, Loss: 0.3466
Epoch 360, Loss: 0.3466
Epoch 400, Loss: 0.3466
Epoch 440, Loss: 0.3466
Epoch 480, Loss: 0.3466
生成结果: helol
